# Site settings
title: Jarvis's Blog
SEOTitle: Jarvis的博客 | Jarvis Blog
header-img: img/home-bg.jpg
email: duanyajuzi@outlook.com
description: " - jarvis，tech Lover - 这里是 @jarvis 的个人博客，与你一起。"
keyword: "jarvis, @jarvis_dev, duanyajuzi, @duanyajuzi"
url: "https://duanyajuzi.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     5897971583
#zhihu_username:
#jianshu_username: 
github_username: duanyajuzi
#mail_username: duanyajuzi@outlook.com
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1                       # use Github Flavored Markdown !important

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true


# Disqus settings
#disqus_username: _your_disqus_short_name_



# Analytics settings
# Baidu Analytics
ba_track_id: 04a5dc85a658b1b97e4afff0f7e44936
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "性喜静 意清幽。"
sidebar-avatar: /images/tx.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Jasper's Blog",
        href: "http://www.4coding.cn/"
    },{
        title: "Remy's Blog",
        href: "http://remyhan.com/"
    },{
        title: "Lee's Blog",
        href: "http://devlz.com/"
    }
]
